spinframework/spin-operator

.github/workflows/publish.yaml
This _should_ fix GitHub showing the README in the multi-arch images...
=> docker: annotate images

charts/spin-operator/templates/NOTES.txt
This PR updates the notes being displayed after installing the Spin Operator helm chart. 
It instructs users to apply both: the SpinAppExecutor and the RuntimeClass from the GitHub tag instead of using release artifacts. 
Before, users were asked to apply the SpinAppExecutor using a non-existent release artifact
=> Update instructions of the Spin-Operator helm chart

.github/workflows/e2e.yaml, Makefile, e2e/README.md, e2e/crd_installed_test.go, e2e/default_test.go, e2e/k3d_provider.go, e2e/main_test.go, go.mod, go.sum
+ adds a simple e2e test for the containerd executor
=> adds basic setup for e2e testing

internal/controller/spinapp_controller.go
This ensures that secrets are deleted when the app is.
We still don't have a way to automatically delete previous versions of the secret, but that's a less important problem than ensuring they go away when the app does.
closes #151
=> runtimeconfig: ensure secrets are owned by the spinapp

Makefile, charts/spin-operator/Chart.lock, charts/spin-operator/Chart.yaml, charts/spin-operator/README.md, charts/spin-operator/templates/NOTES.txt, charts/spin-operator/values.yaml, config/chart/values.yaml
Closes https://github.com/spinkube/spin-operator/issues/108
Tracking docs updates in https://github.com/spinkube/documentation/pull/79
=> ref(chart): remove kwasm-operator sub-chart

config/samples/hpa.yaml, config/samples/keda-app.yaml
With this commit samples for HPA and KEDA will pull Spin App images from ghcr.io instead of ttl.sh
=> Reference `cpu-load-gen` image from ghcr.io

config/samples/keda-app.yaml
Remove the `replicas` configuration per operator error:
```
$ k apply -f config/samples/keda-app.yaml
The SpinApp "keda-spinapp" is invalid: spec.replicas: Invalid value: 1: replicas cannot be set when autoscaling is enabled
```
=> fix(samples): rm replicas config from keda-app

.github/workflows/publish.yaml
- Add a published artifacts summary to the `publish.yaml` workflow, eg
=> ci(publish.yaml): add step summary with artifact references

Makefile, charts/spin-operator/README.md, charts/spin-operator/templates/NOTES.txt, scripts/update-chart-versions.sh
- Templatize the chart README.md for injecting app and chart version at publish time
- Update NOTES.txt
=> docs(chart): templatize/update README and NOTES

README.md
The formatting/templating characters on the pages linked from the README are distracting. This PR swaps the links to the markdown files for the matching links on the spinkube.dev site.
Also fixes the first link which is currently broken.
=> swap md links to spinkube.dev links

cmd/main.go, config/rbac/role.yaml, internal/controller/spinapp_controller.go, internal/controller/spinappexecutor_controller.go, internal/controller/spinappexecutor_controller_test.go
=> Emit k8s event when deleting SpinAppExecutor is blocked because of dependent SpinApps

internal/controller/deployment.go, internal/controller/deployment_test.go, internal/controller/spinapp_controller.go
This is currently a "practical no-op", as we default to setting the value to the Spin Default.
It does however simplify a future, bigger, change to allow non-80 listen addresses with the container to reduce the priviliges that we give to the shim (e.g runAsNonRoot).
=> deployment: Set SPIN_HTTP_LISTEN_ADDR env var

.github/workflows/build.yaml, Makefile
When we added e2e tests, we split them into a separate job and introduced `make e2e`,  but in the process didn't _exclude_ them from other test execution, which means we've been inadvertently slowing down our build pipelines and development flow (executing e2e's twice when running `make test e2e`).
This PR adds those skips.
=> tests: skip e2e by default

.github/CODEOWNERS
Rajat has been instrumental in the development of the Spin Operator and after discussion amongst the existing maintainers we would like to offer an invitation to join the core maintainer team.
Welcome @rajatjindal :tada:
(After Rajat approves this PR I'll add him to the GitHub team before merging, which will un-break the CODEOWNERS linter)
=> maintainers: Add Rajat Jindal

e2e/default_test.go, internal/controller/deployment_test.go, internal/controller/spinapp_controller_test.go
Our tests for the Spin CA don't validate that the resulting TLS bundle is used by the shim, so migrate the core of the tests to lighterweight integration and unit tests.
A future E2E that installs a bundle and validates outbound-tls would also be excellent.
I've avoided adding net-new tests here (as a refactor), but intend to follow up in a new PR with tests that cover the pre-existing secret cases, alongside drafts of how we may version the CA bundle.
=> spin-ca: Migrate tests from E2E to unit and integration

internal/controller/spinapp_controller.go
Eventually we will want to upgrade caBundles to new versions as certificates expire/are rotated/new ca's form. We should however only do that when we manage the resource that is created.
Here we introduce a managed-by annotation that we can use to ensure that we don't replace user-managed secret bundles in the future.
=> ca-secrets: Annotate secrets that are created by spin-operator

.devcontainer.json, Makefile, e2e/k3d_provider.go
I've been experimenting with devcontainers lately after moving more of my personal compute infra to kubernetes - and trying to have smaller environments.
This is a wip devcontainer setup for spinkube that allows you to also successfully run e2e's without overly complex requirements around systemd hierarchies or having _docker_ on the host itself for dind.
Primarily tested with [DevPod](devpod.sh) backed by Kubernetes, but _should_ work with most container hosts.
=> Add support for devcontainers

e2e/default_test.go, e2e/main_test.go
While working on adding a new e2e to exercise runtimeConfig options, I realized that our E2Es are slow partially because we have extended intervals for `wait` events - at 30s. This is unfortunate as _the first check_ isn't even called for that 30s period, and meant that the no-op "wait for object to exist" also took 30s.
This speeds up e2es by removing extra `wait`s, and reducing intervals to allow tests to make progress faster when not blocked on a slow network/very slow cpus, without making things _worse_ in those cases.
We also move creating the executor into the test setup, as it's required for all tests, and we don't currently do per-test namespaces.
=> e2e: speed up

charts/spin-operator/templates/manager-rbac.yaml
After we updated the operator RBAC to include Events, we never updated the checked in version of the chart to reflect that.
This doesn't effect releases, as CI regenerates the helm chart, but does impact people who checkout the repository and use the local helm chart.
=> helm: fix generated chart RBAC

charts/spin-operator/templates/deployment.yaml, config/manager/manager.yaml
We only build images for linux, arm64 and amd64, correctly reflect that in deployment manifests to avoid running on unsupported nodes.
=> operator deployments: Only run on supported architectures

e2e/helper/helper.go, e2e/redis_test.go, e2e/spintainer_test.go, internal/controller/spinapp_controller.go
Closes #319.
I tested locally to make sure that this works both when runtime config is specified and when it isn't.
=> Support runtime config in the spintainer executor

config/crd/bases/core.spinoperator.dev_spinapps.yaml, config/manager/kustomization.yml, e2e/default_test.go, e2e/helper/helper.go, e2e/k3d_provider.go, e2e/redis_test.go, e2e/selective_deployment_test.go
Draft until https://github.com/spinkube/spin-operator/pull/323 merges and new version of the shim is released. For now this updates the tests to point to a canary release of the shim (in k3d).
=> Component filtering e2e test

charts/spin-operator/README.md, charts/spin-operator/templates/NOTES.txt, charts/spin-operator/values.yaml
This PR changes "spinkube" to "spinframework" in the helm chart's links.
More importantly, it also changes the helm chart's default image repository to "ghcr.io/spinframework".
Signed-off-by: Jiaxiao (mossaka) Zhou <duibao55328@gmail.com>
=> charts: spinkube -> spinframework for all links

CONTRIBUTING.md, Makefile, RELEASE.md, config/chart/values.yaml, config/manager/manager.yaml, config/samples/hpa.yaml, config/samples/keda-app.yaml, config/samples/otel.yaml, config/samples/redis.yaml, config/samples/selective-deployment.yaml, config/samples/spintainer.yaml, e2e/selective_deployment_test.go, e2e/spintainer_test.go, scripts/update-chart-versions.sh
Ref https://github.com/spinframework/spin-operator/issues/408
Updates the ghcr/github org from `spinkube` to `spinframework`.
We'll probably want to cut a 0.6.1 release with these changes, to fix the behavior mentioned in https://github.com/spinframework/spin-operator/issues/408.
_(Note: I see we had intended to update the operator image in the chart's values.yaml in https://github.com/spinframework/spin-operator/pull/382, but alas the value needs to be updated under `config/chart/values.yaml` for it to take effect, as the chart is regenerated via `helmify` when packaging up on a release.)_
TODO:
=> chore/fix(*): s/spinkube/spinframework for ghcr and github org
