config/samples/runtime-config.yaml
Fixes the runtime-config sample
=> Fix runtime-config sample

internal/controller/spinapp_controller.go, internal/controller/spinapp_controller_test.go
=> fix runtime config reconcile

charts/spin-operator/templates/manager-rbac.yaml
This was brought in from regenerating the chart from `main`
=> chore(chart): updates from helm-generate

Makefile
=> change chart registry to ghcr.io/spinkube/charts

.github/workflows/publish.yaml
=> publish: push chart to ghcr.io/spinkube/charts/spin-operator

Makefile
Closes https://github.com/spinkube/spin-operator/issues/148
=> fix(Makefile): update runtime-class path under deploy target

internal/runtimeconfig/types.go
Previously if value was `""` we would panic because we would always attempt to load ValueFrom, which can be nil. This is partially a design bug: Empty values aren't _really_ expected to be set. - But Spin _will_ allow them, so we should technically let them be specified?
This allows them to be specified by being a fallback value when nothing else is available, and avoids the panic, which is a bug regardless.
fixes: #174
=> runtimeconfig: Fix a Panic when an empty value is desired

config/samples/cyclotron.yaml, config/samples/kustomization.yaml
This sample app was used in pre-release testing.
=> Remove stale sample

.github/workflows/helm-install-smoketest.yaml, .github/workflows/smoketest.yaml, e2e/k3d_provider.go
This pulls-in the fix for "pod stays in terminating state".
=> use v0.13.1 of shim for tests

charts/spin-operator/templates/NOTES.txt
Signed-off-by: tpmccallum <tim.mccallum@fermyon.com>
Update console output to match the Quickstart documentation (adjust paths to resources)
=> Update CLI output to match documentation

.github/workflows/sample-apps.yaml, apps/outbound-http/.gitignore, apps/outbound-http/go.mod, apps/outbound-http/go.sum, apps/outbound-http/main.go, apps/outbound-http/spin.toml
* will be used for testing default CA bundle feature for supporting outbound http requests
=> add outbound http sample app

api/v1alpha1/spinapp_types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/core.spinoperator.dev_spinapps.yaml, e2e/default_test.go, e2e/main_test.go, e2e/podlabel_test.go, internal/controller/deployment_test.go, internal/controller/spinapp_controller.go, internal/controller/spinapp_controller_test.go
With this PR, users are able to specify labels for underlying pods
closes #225
=> Add podLabels to `SpinApp` CRD

e2e/default_test.go, e2e/main_test.go, internal/controller/spinapp_controller.go
- fixes a bug where using custom name doesn't create the secret
- add test for ensuring ca certificate secret
Closes #234
=> fix(certs): respect the secret name provided in the executor

internal/webhook/spinapp_validating.go, internal/webhook/spinapp_validating_test.go
=> Improve executor not found error

CODE_OF_CONDUCT.md
Discovered while working on https://github.com/spinkube/documentation/pull/210.
=> fix link to Code of Conduct

README.md
See https://github.com/spinkube/documentation/pull/210
=> move "running locally" into the README

.github/workflows/build.yaml, .github/workflows/e2e.yaml, .github/workflows/helm-install-smoketest.yaml, .github/workflows/publish.yaml, .github/workflows/smoketest.yaml, Dockerfile, flake.lock, flake.nix, go.mod
=> Update to go1.23

RELEASE.md
Signed-off-by: Matthew Fisher <matt.fisher@fermyon.com>
=> add release process

e2e/selective_deployment_test.go, e2e/spintainer_test.go
Only final commit is the test. First 3 come from https://github.com/spinkube/spin-operator/pull/339 and https://github.com/spinkube/spin-operator/pull/328
=> Spintainer selective deployment test

.github/workflows/sample-apps.yaml
Sample app builds are failing https://github.com/spinkube/spin-operator/actions/runs/11562214870/job/32182895605.
This might fix it. Not sure how to best test this so feedback on that would be appreciated.
=> fix(ci): Potential fix for sample apps failing to build

charts/spin-operator/Chart.yaml
Re: https://github.com/spinframework/spin-operator/releases/v0.6.1
=> chore(chart): bump chart versions to 0.6.1
